create extension if not exists pgcrypto;

create table if not exists public.admin_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'admin' check (role in ('admin', 'owner')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null,
  price integer not null check (price >= 0),
  image text not null,
  category text not null,
  filters text[] not null default '{}',
  available boolean not null default true,
  featured boolean not null default false,
  tag text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

alter table public.products add column if not exists filters text[] not null default '{}';

create table if not exists public.delivery_zones (
  id text primary key,
  name text not null,
  fee integer not null default 0 check (fee >= 0),
  eta_minutes integer not null default 35 check (eta_minutes > 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity unique,
  lookup_token uuid not null default gen_random_uuid(),
  customer_name text,
  customer_phone text,
  table_number integer,
  order_type text not null,
  notes text,
  subtotal integer not null default 0 check (subtotal >= 0),
  delivery_fee integer not null default 0 check (delivery_fee >= 0),
  delivery_address text,
  delivery_zone_id text references public.delivery_zones(id) on delete set null,
  delivery_zone_name text,
  delivery_reference text,
  delivery_eta_minutes integer,
  payment_method text,
  change_for integer check (change_for is null or change_for >= 0),
  total integer not null default 0 check (total >= 0),
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

-- Columnas agregadas después del primer release: seguras de re-ejecutar.
alter table public.orders add column if not exists subtotal integer not null default 0;
alter table public.orders add column if not exists delivery_fee integer not null default 0;
alter table public.orders add column if not exists delivery_address text;
alter table public.orders add column if not exists delivery_zone_id text references public.delivery_zones(id) on delete set null;
alter table public.orders add column if not exists delivery_zone_name text;
alter table public.orders add column if not exists delivery_reference text;
alter table public.orders add column if not exists delivery_eta_minutes integer;
alter table public.orders add column if not exists payment_method text;
alter table public.orders add column if not exists change_for integer;

alter table public.orders drop constraint if exists orders_order_type_check;
alter table public.orders add constraint orders_order_type_check
  check (order_type in ('table', 'takeaway', 'delivery'));

alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
  check (status in ('pending', 'preparing', 'ready', 'on_the_way', 'completed', 'cancelled'));

alter table public.orders drop constraint if exists orders_payment_method_check;
alter table public.orders add constraint orders_payment_method_check
  check (payment_method is null or payment_method in ('cash', 'transfer', 'card'));

alter table public.orders drop constraint if exists orders_table_or_takeaway_check;
alter table public.orders drop constraint if exists orders_channel_check;
alter table public.orders add constraint orders_channel_check check (
  (order_type = 'table' and table_number is not null)
  or
  (order_type = 'takeaway' and customer_name is not null and customer_phone is not null)
  or
  (
    order_type = 'delivery'
    and customer_name is not null
    and customer_phone is not null
    and delivery_address is not null
    and delivery_zone_name is not null
  )
);

create table if not exists public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  status text not null,
  changed_at timestamptz not null default now()
);

create index if not exists order_status_history_order_idx on public.order_status_history (order_id);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  name text,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0),
  subtotal integer not null check (subtotal >= 0)
);

-- El nombre se copia al momento del pedido para que un plato renombrado o
-- eliminado despues no altere el historico de pedidos ya hechos.
alter table public.order_items add column if not exists name text;

create table if not exists public.tables (
  id uuid primary key default gen_random_uuid(),
  number integer not null unique check (number > 0),
  status text not null default 'free' check (status in ('free', 'occupied')),
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.restaurant_settings (
  id integer primary key default 1 check (id = 1),
  restaurant_name text not null default 'Brasa Marina',
  description text,
  phone text,
  whatsapp text,
  address text,
  hours text,
  instagram text,
  table_count integer not null default 20 check (table_count > 0),
  delivery_enabled boolean not null default true,
  delivery_min_order integer not null default 45000 check (delivery_min_order >= 0),
  updated_at timestamptz not null default now()
);

alter table public.restaurant_settings add column if not exists delivery_enabled boolean not null default true;
alter table public.restaurant_settings add column if not exists delivery_min_order integer not null default 45000;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles
    where user_id = auth.uid()
  );
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at
before update on public.products
for each row execute function public.touch_updated_at();

drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at
before update on public.orders
for each row execute function public.touch_updated_at();

drop trigger if exists tables_touch_updated_at on public.tables;
create trigger tables_touch_updated_at
before update on public.tables
for each row execute function public.touch_updated_at();

-- security definer: el INSERT en order_status_history debe pasar aunque
-- quien actualice el pedido no tenga permiso directo de escritura en esa
-- tabla (solo hay política de lectura para admins).
create or replace function public.record_order_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.status is distinct from old.status then
    insert into public.order_status_history (order_id, status)
    values (new.id, new.status);
  end if;

  -- Un pedido en mesa libera la mesa al cerrarse y la ocupa mientras está vivo.
  if new.table_number is not null then
    update public.tables
    set status = case
      when new.status in ('pending', 'preparing', 'ready', 'on_the_way') then 'occupied'
      else 'free'
    end
    where number = new.table_number;
  end if;

  return new;
end;
$$;

drop trigger if exists orders_record_status on public.orders;
create trigger orders_record_status
after insert or update of status on public.orders
for each row execute function public.record_order_status();

drop function if exists public.create_public_order(text, text, integer, text, text, jsonb);

create or replace function public.create_public_order(
  input_customer_name text,
  input_customer_phone text,
  input_table_number integer,
  input_order_type text,
  input_notes text,
  input_items jsonb,
  input_delivery_zone_id text default null,
  input_delivery_address text default null,
  input_delivery_reference text default null,
  input_payment_method text default null,
  input_change_for integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order public.orders;
  item jsonb;
  product_row public.products;
  zone_row public.delivery_zones;
  settings_row public.restaurant_settings;
  order_subtotal integer := 0;
  order_fee integer := 0;
begin
  if input_order_type not in ('table', 'takeaway', 'delivery') then
    raise exception 'Tipo de pedido inválido.';
  end if;

  if jsonb_typeof(input_items) <> 'array' or jsonb_array_length(input_items) = 0 then
    raise exception 'El pedido no tiene productos.';
  end if;

  select * into settings_row from public.restaurant_settings where id = 1;

  if input_order_type = 'table' and input_table_number is null then
    raise exception 'Selecciona una mesa.';
  end if;

  if input_order_type <> 'table'
     and (nullif(trim(input_customer_name), '') is null or nullif(trim(input_customer_phone), '') is null) then
    raise exception 'Nombre y teléfono son obligatorios para este tipo de pedido.';
  end if;

  -- Los precios y el costo de envío se calculan siempre desde la base de datos,
  -- nunca desde el payload del cliente.
  for item in select * from jsonb_array_elements(input_items)
  loop
    select *
    into product_row
    from public.products
    where id = (item ->> 'product_id')::uuid
      and available = true;

    if product_row.id is null then
      raise exception 'Uno de los productos no está disponible.';
    end if;

    order_subtotal := order_subtotal + product_row.price * greatest((item ->> 'quantity')::integer, 1);
  end loop;

  if input_order_type = 'delivery' then
    if not coalesce(settings_row.delivery_enabled, true) then
      raise exception 'Los domicilios están desactivados en este momento.';
    end if;

    select * into zone_row
    from public.delivery_zones
    where id = input_delivery_zone_id and active = true;

    if zone_row.id is null then
      raise exception 'Selecciona una zona de entrega válida.';
    end if;

    if length(coalesce(trim(input_delivery_address), '')) < 8 then
      raise exception 'Escribe una dirección de entrega completa.';
    end if;

    if order_subtotal < coalesce(settings_row.delivery_min_order, 0) then
      raise exception 'El pedido no alcanza el mínimo para domicilio.';
    end if;

    order_fee := zone_row.fee;
  end if;

  insert into public.orders (
    customer_name,
    customer_phone,
    table_number,
    order_type,
    notes,
    subtotal,
    delivery_fee,
    delivery_address,
    delivery_zone_id,
    delivery_zone_name,
    delivery_reference,
    delivery_eta_minutes,
    payment_method,
    change_for,
    total,
    status
  )
  values (
    nullif(trim(input_customer_name), ''),
    nullif(trim(input_customer_phone), ''),
    case when input_order_type = 'table' then input_table_number else null end,
    input_order_type,
    nullif(trim(input_notes), ''),
    order_subtotal,
    order_fee,
    case when input_order_type = 'delivery' then trim(input_delivery_address) else null end,
    case when input_order_type = 'delivery' then zone_row.id else null end,
    case when input_order_type = 'delivery' then zone_row.name else null end,
    case when input_order_type = 'delivery' then nullif(trim(input_delivery_reference), '') else null end,
    case when input_order_type = 'delivery' then zone_row.eta_minutes else null end,
    case when input_order_type = 'delivery' then coalesce(input_payment_method, 'cash') else null end,
    case when input_order_type = 'delivery' and input_payment_method = 'cash' then input_change_for else null end,
    order_subtotal + order_fee,
    'pending'
  )
  returning * into new_order;

  for item in select * from jsonb_array_elements(input_items)
  loop
    select * into product_row
    from public.products
    where id = (item ->> 'product_id')::uuid;

    insert into public.order_items (order_id, product_id, name, quantity, unit_price, subtotal)
    values (
      new_order.id,
      product_row.id,
      product_row.name,
      greatest((item ->> 'quantity')::integer, 1),
      product_row.price,
      product_row.price * greatest((item ->> 'quantity')::integer, 1)
    );
  end loop;

  return jsonb_build_object(
    'id', new_order.id,
    'number', new_order.number,
    'lookup_token', new_order.lookup_token,
    'status', new_order.status,
    'subtotal', new_order.subtotal,
    'delivery_fee', new_order.delivery_fee,
    'total', new_order.total
  );
end;
$$;

create or replace function public.get_public_order(
  input_number bigint,
  input_lookup_token uuid
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id', o.id,
    'number', o.number,
    'customer_name', o.customer_name,
    'customer_phone', o.customer_phone,
    'table_number', o.table_number,
    'order_type', o.order_type,
    'notes', o.notes,
    'subtotal', o.subtotal,
    'delivery_fee', o.delivery_fee,
    'total', o.total,
    'status', o.status,
    'created_at', o.created_at,
    'delivery', case
      when o.order_type = 'delivery' then jsonb_build_object(
        'address', o.delivery_address,
        'zone_id', o.delivery_zone_id,
        'zone_name', o.delivery_zone_name,
        'reference', o.delivery_reference,
        'eta_minutes', o.delivery_eta_minutes
      )
      else null
    end,
    'payment', case
      when o.payment_method is null then null
      else jsonb_build_object('method', o.payment_method, 'change_for', o.change_for)
    end,
    'status_history', coalesce(
      (
        select jsonb_agg(jsonb_build_object('status', h.status, 'at', h.changed_at) order by h.changed_at)
        from public.order_status_history h
        where h.order_id = o.id
      ),
      '[]'::jsonb
    ),
    'items', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'name', coalesce(oi.name, p.name, 'Producto eliminado'),
          'quantity', oi.quantity,
          'unit_price', oi.unit_price,
          'subtotal', oi.subtotal
        )
      ) filter (where oi.id is not null),
      '[]'::jsonb
    )
  )
  from public.orders o
  left join public.order_items oi on oi.order_id = o.id
  left join public.products p on p.id = oi.product_id
  where o.number = input_number
    and o.lookup_token = input_lookup_token
  group by o.id;
$$;

-- Habilita eventos en vivo (Realtime) para que el panel admin y el sitio
-- publico reciban cambios sin necesidad de recargar la pagina.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders') then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'order_items') then
    alter publication supabase_realtime add table public.order_items;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'products') then
    alter publication supabase_realtime add table public.products;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tables') then
    alter publication supabase_realtime add table public.tables;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'restaurant_settings') then
    alter publication supabase_realtime add table public.restaurant_settings;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'delivery_zones') then
    alter publication supabase_realtime add table public.delivery_zones;
  end if;
end $$;

alter table public.admin_profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;
alter table public.delivery_zones enable row level security;
alter table public.tables enable row level security;
alter table public.restaurant_settings enable row level security;

drop policy if exists "Admins can manage admin profiles" on public.admin_profiles;
create policy "Admins can manage admin profiles"
on public.admin_profiles
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Los agotados se muestran igual en la carta con la etiqueta "Agotado"
-- (mejor experiencia que ocultarlos): no hay dato sensible en un producto.
drop policy if exists "Public can read available products" on public.products;
drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products"
on public.products
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage orders" on public.orders;
create policy "Admins can manage orders"
on public.orders
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage order items" on public.order_items;
create policy "Admins can manage order items"
on public.order_items
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can read status history" on public.order_status_history;
create policy "Admins can read status history"
on public.order_status_history
for select
to authenticated
using (public.is_admin());

drop policy if exists "Public can read active delivery zones" on public.delivery_zones;
create policy "Public can read active delivery zones"
on public.delivery_zones
for select
to anon, authenticated
using (active = true);

drop policy if exists "Admins can manage delivery zones" on public.delivery_zones;
create policy "Admins can manage delivery zones"
on public.delivery_zones
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read tables" on public.tables;
create policy "Public can read tables"
on public.tables
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can manage tables" on public.tables;
create policy "Admins can manage tables"
on public.tables
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read settings" on public.restaurant_settings;
create policy "Public can read settings"
on public.restaurant_settings
for select
to anon, authenticated
using (true);

drop policy if exists "Admins can manage settings" on public.restaurant_settings;
create policy "Admins can manage settings"
on public.restaurant_settings
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant execute on function public.create_public_order(
  text, text, integer, text, text, jsonb, text, text, text, text, integer
) to anon, authenticated;
grant execute on function public.get_public_order(bigint, uuid) to anon, authenticated;
